from typing import Protocol
from uuid import UUID

from app.domain.models import Itinerary, ItineraryCreatedEvent, OutboxEvent


class AirportClientPort(Protocol):
    async def exists(self, airport_id: int, token: str) -> bool: ...


class ItineraryRepositoryPort(Protocol):
    async def add(self, itinerary: Itinerary) -> None: ...
    async def get(self, itinerary_id: UUID, user_id: str) -> Itinerary | None: ...
    async def list(self, user_id: str, offset: int, limit: int) -> list[Itinerary]: ...
    async def update(self, itinerary: Itinerary) -> None: ...
    async def delete(self, itinerary_id: UUID, user_id: str) -> bool: ...


class OutboxRepositoryPort(Protocol):
    async def add(self, event: OutboxEvent) -> None: ...


class UnitOfWorkPort(Protocol):
    itineraries: ItineraryRepositoryPort
    outbox: OutboxRepositoryPort

    async def __aenter__(self) -> "UnitOfWorkPort": ...
    async def __aexit__(self, exc_type, exc, tb) -> None: ...


class EventEncoderPort(Protocol):
    def encode(self, event: ItineraryCreatedEvent) -> OutboxEvent: ...
